### ISSUE TITLE
ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by anhtuannbk** [healx/lig3dlens#15]
When I use the 

```
!lig3dlens-align --ref reference_mol.smi --lib filted_Enamine_hts_collection_202303_first500.sdf --conf 500 --out conf_filted_Enamine_hts_collection_202303_first500.sdf
``` 

command, I get an error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/lig3dlens-align", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lig3dlens/main.py", line 55, in main
    run_alignment(search_config, num_conformers, output_file)
  File "/usr/local/lib/python3.10/dist-packages/lig3dlens/alignment.py", line 55, in run_alignment
    with multiprocessing.Pool(num_processes) as pool:
  File "/usr/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

Does anyone have the same error as me? And is there any way to debug it?

**Comment by danodonovan** [comment]
Thanks @anhtuannbk -- the latest version of the library should fix this issue for you now. You will need to fetch and merge the latest changes with your local checkout. Either 

* (in your lig3dlens directory) run 
    * `git stash` (save local changes for later)
    * `git fetch` (pull the fix for the code)
    * `git rebase origin/main` (apply the fix)
    * `git stash pop` (return your files to the previous state)
    * `pip install -U -r requirements.txt` (to update the install)
    
 OR 
 
 * edit `/usr/local/lib/python3.10/dist-packages/lig3dlens/alignment.py` file
     * remove line 55 `num_processes = multiprocessing.cpu_count() - 2`
     * update line 56 to be `with multiprocessing.Pool() as pool:`
     
Thank you for reporting, I hope the fix works
