### ISSUE TITLE
AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment'

### ISSUE THREAD

**Issue by Evert-Homan** [healx/lig3dlens#19]
Hi,

I tried to install on another machine (Ubuntu 22.04) in a new conda environment. When running the example I get:

```
lig3dlens-prepare --in tests/test_data/Enamine_hts_collection_202303_first500_VS_results.sdf     --filter lig3dlens/physchem_properties.yaml     --out curated_compounds.sd
2024-04-30 13:45:17.177 | INFO     | lig3dlens.prep_cmpd_library:main:119 - Initialising the compound library preparation workflow
2024-04-30 13:45:17.177 | INFO     | lig3dlens.prep_cmpd_library:main:125 - Loading cmpds from tests/test_data/Enamine_hts_collection_202303_first500_VS_results.sdf to a Pandas dataframe
Traceback (most recent call last):
  File "/home/evehom/miniconda3/envs/lig3dlens/bin/lig3dlens-prepare", line 8, in <module>
    sys.exit(main())
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/lig3dlens/prep_cmpd_library.py", line 128, in main
    mols_lib = dm.read_sdf(input_cmpd_lib, as_df=True, mol_column="ROMol")
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/datamol/__init__.py", line 186, in __getattr__
    mod = importlib.import_module(obj_mod)
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/datamol/io.py", line 16, in <module>
    from rdkit.Chem import PandasTools
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/rdkit/Chem/PandasTools.py", line 653, in <module>
    InstallPandasTools()
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/rdkit/Chem/PandasTools.py", line 622, in InstallPandasTools
    PandasPatcher.patchPandas()
  File "/home/evehom/miniconda3/envs/lig3dlens/lib/python3.10/site-packages/rdkit/Chem/PandasPatcher.py", line 263, in patchPandas
    if getattr(pandas_formats.format, get_adjustment_name) != patched_get_adjustment:
AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment'
```

Any clues what is causing this? Thank you,

Evert

**Comment by bill-tatsis** [comment]
Hi Evert, 
It must be related to this [issue](https://github.com/rdkit/rdkit/pull/7165) with Pandas 2.2.0 "_Starting from pandas 2.2.0, the get_adjustment function is no longer in the pandas.io.formats.format module, but in the pandas.io.formats.printing module (cf. [pandas/blob/2.2.x/pandas/io/formats/format.py#L223](https://github.com/pandas-dev/pandas/blob/3dca4f0f8d583c67d2df56bf9ba51839cdaa6d26/pandas/io/formats/format.py#L223) vs [pandas/blob/2.1.x/pandas/io/formats/format.py#L293](https://github.com/pandas-dev/pandas/blob/a671b5a8bf5dd13fb19f0e88edc679bc9e15c673/pandas/io/formats/format.py#L293))._"

Can you try installing an earlier version of pandas (2.1)?

Best,
Bill

**Comment by Evert-Homan** [comment]
Hi Bill, thanks for your reply. I could resolve the issue by activating the lig3dlens conda environment and then run

`conda install pandas=2.1`

Best wishes/Evert

**Comment by NaveedUrRehman787** [comment]
> Hi Evert, It must be related to this [issue](https://github.com/rdkit/rdkit/pull/7165) with Pandas 2.2.0 "_Starting from pandas 2.2.0, the get_adjustment function is no longer in the pandas.io.formats.format module, but in the pandas.io.formats.printing module (cf. [pandas/blob/2.2.x/pandas/io/formats/format.py#L223](https://github.com/pandas-dev/pandas/blob/3dca4f0f8d583c67d2df56bf9ba51839cdaa6d26/pandas/io/formats/format.py#L223) vs [pandas/blob/2.1.x/pandas/io/formats/format.py#L293](https://github.com/pandas-dev/pandas/blob/a671b5a8bf5dd13fb19f0e88edc679bc9e15c673/pandas/io/formats/format.py#L293))._"
> 
> Can you try installing an earlier version of pandas (2.1)?
> 
> Best, Bill

Than

**Comment by bill-tatsis** [comment]
No worries Bro! Godspeed to your VS campaigns 🤘🏽
